steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/handx-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/handx-api']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'handx-digit-recognition'
      - '--image'
      - 'gcr.io/$PROJECT_ID/handx-api'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,PORT=8080'
images:
  - 'gcr.io/$PROJECT_ID/handx-api'

